name: Test

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Save Points Marketplace Identities
      run: echo "Hello!" >> test.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update"
        branch: main
        file_pattern: '*.txt'
  